"""followers

Revision ID: 57783dfe64a7
Revises: 11c7e5bf2ae1
Create Date: 2022-11-07 14:44:30.251086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57783dfe64a7'
down_revision = '11c7e5bf2ae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
